intro_assignment/intro_assignment/urls.py
import imp
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intro_assignment/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', showmain, name= 'showmain'),
    path('mainpage/', showpage, name= 'showpage'),
    path('<int:id>', detail, name='detail'),
    path('new/', new, name='new'),
    path('create/', create, name="create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<int:post_id>/create_comment', create_comment, name='create_comment'),
    path('delete_comment/<int:id>', delete_comment, name="delete_comment"),
    path('edit_comment/<int:id>', edit_comment, name="edit_comment"),
    path('update_comment/<int:id>', update_comment, name="update_comment"),
    path('like_toggle/<int:post_id>/', like_toggle, name="like_toggle"),
    path('my_like/<int:user_id>', my_like, name='my_like'),
    path('dislike_toggle/<int:post_id>/', dislike_toggle, name="dislike_toggle"),
    path('my_dislike/<int:user_id>', my_dislike, name='my_dislike'),
]

intro_assignment/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:user_id>', mypage, name="mypage"),
    path('follow/<int:user_id>', follow, name="follow")
]

intro_assignment/intro_assignment/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:showmain' %}">동대 멋사 10기♥</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Account
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">로그아웃</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:mypage' request.user.id %}">마이페이지</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:my_like' request.user.id  %}">내 좋아요 목록</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:my_dislike' request.user.id  %}">내 싫어요 목록</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'account_login' %}">로그인</a></li>
                        <li><a class="dropdown-item" href="{% url 'account_signup' %}">회원가입</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>