intro_assignment/intro_assignment/urls.py
import imp
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intro_assignment/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', showmain, name= 'showmain'),
    path('mainpage/', showpage, name= 'showpage'),
    path('<int:id>', detail, name='detail'),
    path('new/', new, name='new'),
    path('create/', create, name="create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<int:post_id>/create_comment', create_comment, name='create_comment'),
    path('delete_comment/<int:id>', delete_comment, name="delete_comment"),
    path('edit_comment/<int:id>', edit_comment, name="edit_comment"),
    path('update_comment/<int:id>', update_comment, name="update_comment"),
    path('like_toggle/<int:post_id>/', like_toggle, name="like_toggle"),
    path('my_like/<int:user_id>', my_like, name='my_like'),
    path('dislike_toggle/<int:post_id>/', dislike_toggle, name="dislike_toggle"),
    path('my_dislike/<int:user_id>', my_dislike, name='my_dislike'),
]

intro_assignment/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:user_id>', mypage, name="mypage"),
    path('follow/<int:user_id>', follow, name="follow")
]

intro_assignment/main/models.py
from msilib.schema import Property
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "post/", blank=True, null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name="like_user_set", through='Like')
    dislike_user_set = models.ManyToManyField(User, blank=True, related_name="dislike_user_set", through="Dislike")

    @property
    def like_count(self):
        return self.like_user_set.count()

    @property
    def dislike_count(self):
        return self.dislike_user_set.count()

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now=True)
    update_at = models.DateTimeField(auto_now=True)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user', 'post'))

class Dislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user', 'post'))

intro_assignment/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, Like, Dislike
from django.utils import timezone
from django.db import models
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import json
from django.contrib.auth.models import User

# Create your views here.
def showmain(request):
    posts = Post.objects.all()
    return render(request, 'main/show.html', {'posts':posts})

def showpage(request):
    return render(request, 'main/mainpage.html')

def detail(request, id):
    post = get_object_or_404(Post, pk = id)
    all_comments = post.comments.all().order_by('-created_at')
    return render(request, 'main/detail.html', {'post': post, 'comments':all_comments})

def new(request):
    return render(request, 'main/new.html')

def create(request):
    new_post = Post()
    new_post.title = request.POST['title']
    new_post.writer = request.user
    new_post.pub_date = timezone.now()
    new_post.body = request.POST['body']
    new_post.image = request.FILES.get('image')
    new_post.save()
    return redirect('main:detail', new_post.id)

def edit(request, id):
    edit_post = Post.objects.get(id = id)
    return render(request, 'main/edit.html', {'post' : edit_post})

def update(request, id):
    update_post = Post.objects.get(id = id)
    update_post.title = request.POST['title']
    update_post.writer = request.user
    update_post.pub_date = timezone.now()
    update_post.image = request.FILES.get('image')
    update_post.body = request.POST['body']
    update_post.save()
    return redirect('main:detail', update_post.id)

def delete(request, id):
    delete_post = Post.objects.get(id = id)
    delete_post.delete()
    return redirect('main:showmain')

def create_comment(request, post_id):
    new_comment = Comment()
    new_comment.writer = request.user
    new_comment.content = request.POST['content']
    new_comment.post = get_object_or_404(Post, pk = post_id)
    new_comment.save()
    return redirect('main:detail', post_id)

def delete_comment(request,id):
    comment = get_object_or_404(Comment, pk=id)
    post_id = comment.post.id
    comment.delete()
    return redirect('main:detail', post_id)

def edit_comment(request, id):
    edit_comment = Comment.objects.get(id = id)
    return render(request, 'main/edit_comment.html', {'comment' : edit_comment})

def update_comment(request, id):
    print("update Comment content = " + request.POST['content'])
    update_comment = Comment.objects.get(id = id)
    update_comment.content = request.POST['content']
    update_comment.update_at = models.DateTimeField(auto_now=True)
    update_comment.save()
    return redirect('main:detail', update_comment.post.id)

@require_POST
@login_required
def like_toggle(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    post_like, post_like_created = Like.objects.get_or_create(user = request.user, post=post)

    if not post_like_created:
        post_like.delete()
        result = "cancelled"

    else:
        result = "like"
    
    context = {
        "like_count" : post.like_count,
        "result" : result
    }

    return HttpResponse(json.dumps(context), content_type = "application/json")

def my_like(request, user_id):
    user = User.objects.get(id=user_id)
    like_list = Like.objects.filter(user = user)
    context = {
        'like_list' : like_list,
    } 

    return render(request, 'main/my_like.html', context)

@require_POST
@login_required
def dislike_toggle(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    post_dislike, post_dislike_created = Dislike.objects.get_or_create(user = request.user, post=post)

    if not post_dislike_created:
        post_dislike.delete()
        result = "cancelled"

    else:
        result = "dislike"
    
    context = {
        "dislike_count" : post.dislike_count,
        "result" : result
    }

    return HttpResponse(json.dumps(context), content_type = "application/json")

def my_dislike(request, user_id):
    user = User.objects.get(id=user_id)
    dislike_list = Dislike.objects.filter(user = user)
    context = {
        'dislike_list' : dislike_list,
    } 

    return render(request, 'main/my_dislike.html', context)

    

intro_assignment/main/templates/main/detail.html
{% extends 'base.html' %}
% load static %

{% block content %}
<h1>{{post.title}}</h1>
{% if post.writer %}
<a href="{% url 'users:mypage' post.writer.id %}"></a>
    {% if 'user' in post.writer.username %}
        <h3>작성자 : <a href="{% url 'users:mypage' post.writer.id %}">{{post.writer.last_name}} {{post.writer.first_name}}</a></h3>

    {% else %}
        <h3>작성자 : <a href="{% url 'users:mypage' post.writer.id %}">{{post.writer}}</a></h3>
    {% endif %}
{% else %}
    <h3>작성자 : 알 수 없음</h3>
{% endif %}

날짜: {{post.pub_date}}
<hr>
{% if post.image %}
<p><img src="{{ post.image.url }}" alt="사진"></p>
{% endif %}

<p>{{post.body}}</p>

<span href="#" class="like" name ="{{post.id}}" value="Like">
    {% if user in post.like_user_set.all %}
        <div class="alt-service-icon">
            <i class="fas fa-heart" id ="like-icon" style="color:red;"></i>
        </div>
    {% else %}
            <div class="alt-service-icon">
            <i class="far fa-heart" id ="like-icon" style="color:red;"></i>
        </div>
    {% endif %}
        <span id="count-{{ post.id }}" class="alt-services-title font-alt">
            좋아요
        {% if post.like_count == 0 %}
            0개
        {% else %}
            {{ post.like_count }}개
         {% endif %}
        </span>
</span>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    $(".like").click(function(){
        var pk=$(this).attr('name')
        $.ajax({
             type:'POST',
            url:"{% url 'main:like_toggle' post.pk %}",
            data:{'pk':pk,'csrfmiddlewaretoken':'{{csrf_token}}'},
            dataType:'json',
            success:function(response){
                if(response.like_count==null){
                    alert('로그인이 필요합니다.');
                     window.location.replace('/accounts/login/');
                }
                else{
                    if(response.result=='like'){
                       $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-heart');
                    }
                    else{
                         $('#like-icon').removeClass();
                        $('#like-icon').addClass('far fa-heart');
                     }
                    $('#count-{{post.id}}').html('좋아요'+response.like_count+"개");
                 }
            },
             error:function(request, status, error){
                alert("로그인이 필요합니다.")
                alert('code:'+request.status+'\n'+'message:'+request.responseText+"\n"+"error:"+error);
            },
         })
    })
</script>

<span href="#" class="dislike" name ="{{post.id}}" value="Dislike">
    {% if user in post.dislike_user_set.all %}
        <div class="alt-service-icon">
            <i class="fas fa-heart" id ="dislike-icon" style="color:red;"></i>
        </div>
    {% else %}
            <div class="alt-service-icon">
            <i class="far fa-heart" id ="dislike-icon" style="color:red;"></i>
        </div>
    {% endif %}
        <span id="discount-{{ post.id }}" class="alt-services-title font-alt">
            싫어요
        {% if post.dislike_count == 0 %}
            0개
        {% else %}
            {{ post.dislike_count }}개
         {% endif %}
        </span>
</span>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    $(".dislike").click(function(){
        var pk=$(this).attr('name')
        $.ajax({
             type:'POST',
            url:"{% url 'main:dislike_toggle' post.pk %}",
            data:{'pk':pk,'csrfmiddlewaretoken':'{{csrf_token}}'},
            dataType:'json',
            success:function(response){
                if(response.dislike_count==null){
                    alert('로그인이 필요합니다.');
                     window.location.replace('/accounts/login/');
                }
                else{
                    if(response.result=='dislike'){
                       $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('fas fa-heart');
                    }
                    else{
                         $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('far fa-heart');
                     }
                    $('#discount-{{post.id}}').html('싫어요'+response.dislike_count+"개");
                 }
            },
             error:function(request, status, error){
                alert("로그인이 필요합니다.")
                alert('code:'+request.status+'\n'+'message:'+request.responseText+"\n"+"error:"+error);
            },
         })
    })
</script>

{% if user.is_authenticated %}
{% if user == post.writer %}
<a href="{%url 'main:edit' post.id%}">수정하기</a>
<a href="{%url 'main:delete' post.id%}">삭제하기</a>
{% endif %}
{% endif %}

<hr>

{% if user.is_authenticated %}
<div>
    <form action="{%url 'main:create_comment' post.id%}" method="POST">
        {%csrf_token%}
        <textarea name="content" placeholder="댓글내용입력"></textarea>
        <input type="submit" value="확인">
    </form>
</div>
{% endif %}

<hr>
<div>
    {% for comment in comments %}
    <div>
        작성자 : <a href="{% url 'users:mypage' post.writer.id %}">{{comment.writer}}</a>
        {{comment.content}}

        {% if user.is_authenticated %}
            {% if user == comment.writer %}
                <a href="{% url 'main:delete_comment' comment.id %}">삭제하기</a>
                <a href="{% url 'main:edit_comment' comment.id %}">수정하기</a>
            {% endif %}
        {% endif %}
        <br>
        <hr>
    </div>
    {% endfor %}
</div>

{% endblock %}

intro_assignment/main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 
<div class="container">
    <h1>글 수정하기</h1>
    <form action="{% url 'main:update' post.id %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목 : <input type="text" name="title" value="{{post.title}}"></p>
        <p>사진: <input type="file" name="image"></p>
        <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10">{{post.body}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</div>

{% endblock %}

intro_assignment/main/templates/main/edit_comment.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 
<div class="container">
    <h1>댓글 수정하기</h1>
    <form action="{% url 'main:update_comment' comment.id %}" method="post">
        {%csrf_token%}
        <p>내용 : <textarea type="text" name="content" id="" cols="30" rows="10">{{comment.content}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</div>

{% endblock %}

intro_assignment/main/templates/main/mainpage.html
{% extends 'base.html' %}

{% block content %}

<h1>안녕하세요. 멋쟁이사자처럼 10기 오민영의 SNS입니다.</h1>
<hr>
<h1>통계학, 프로그래밍에 관심이 있습니다</h1>

{% endblock %}

intro_assignment/main/templates/main/my_dislike.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <p style="font-weight:bold;">🐳 내 싫어요 목록 🐳</p>
        <div class="row">
            {% for dislike in dislike_list %}
                <div class="col-md-3 col-6 item_list__card">
                    <div class="card">
                        {% if dislike.post.image %}
                            <a href="#">
                                <img src="{{ dislike.post.image.url }}" width="100%" height="300px" alt="...">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">{{ dislike.post.title }}</h5>
                                <a href="{% url 'main:detail' dislike.post.pk %}" class="btn btn-outline-primary">보러가기</a>
                               </div>
                        {% else %}
                            <div class="card-body">
                                <h5 class="card-title">{{ dislike.post.title }}</h5>
                                <a href="{% url 'main:detail' dislike.post.pk %}" class="btn btn-outline-primary">보러가기</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

intro_assignment/main/templates/main/my_like.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <p style="font-weight:bold;">🐳 내 좋아요 목록 🐳</p>
        <div class="row">
            {% for like in like_list %}
                <div class="col-md-3 col-6 item_list__card">
                    <div class="card">
                        {% if like.post.image %}
                            <a href="#">
                                <img src="{{ like.post.image.url }}" width="100%" height="300px" alt="...">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">{{ like.post.title }}</h5>
                                <a href="{% url 'main:detail' like.post.pk %}" class="btn btn-outline-primary">보러가기</a>
                               </div>
                        {% else %}
                            <div class="card-body">
                                <h5 class="card-title">{{ like.post.title }}</h5>
                                <a href="{% url 'main:detail' like.post.pk %}" class="btn btn-outline-primary">보러가기</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

intro_assignment/main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{%url 'main:create'%}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <p>제목: <input type="text" name="title"></p>
    <p>사진: <input type="file" name="image"></p>
    <p>내용: <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

intro_assignment/main/templates/main/show.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'main:showpage' %}">Next Page</a>

{% if user.is_authenticated %}
<h2><a href="{%url 'main:new'%}">글쓰기</a></h2>

<h1>글 목록</h1>
{% for post in posts %}
<div>
    <h3>{{post.title}}</h3>
    {% if post.writer %}
        {% if 'user' in post.writer.username %}
            <h3>작성자 : {{ post.writer.last_name }} {{ post.writer.first_name }}</h3>
        {% else %}
            <h3>작성자 : {{ post.writer }}</h3>
        {% endif %}
    {% else %}
        <h3>작성자 : 알 수 없음</h3>
    {% endif %}

    {{post.summary}} <br>
    <a href="{%url 'main:detail' post.id %}">...자세히</a>
</div>
{% endfor %}

{% else %}
<a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
<a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
{% endif %}

<div class="card">
    <div class="card-body">


        <h1 class="card-title">Info</h1>

        <p class="card-text">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Name: 오민영</li>
            <li class="list-group-item">Birthday: 2003. 02. 22.</li>
            <li class="list-group-item">Major: Statistics</li>
            <li class="list-group-item">MBTI: I(E)STP</li>

        </ul>

        </p>


    </div>
</div>

<div class="card">
    <div class="card-body">

        <h1 class="card-title">What I'm learning</h1>

        <p class="card-text">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">English Conversation</li>
            <li class="list-group-item">Python</li>
            <li class="list-group-item">Flutter</li>
            <li class="list-group-item">JavaScript</li>
            <li class="list-group-item">Django</li>
            <li class="list-group-item">Pandas</li>
            <li class="list-group-item">Html/Css</li>

        </ul>
        </p>


    </div>
</div>


<div class="card">
    <div class="card-body">

        <h1 class="card-title">What I Like </h1>

        <p class="card-text">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Learning new things</li>
            <li class="list-group-item">Pikachu</li>

        </ul>
        </p>
    </div>
</div>
{% endblock %}