intro_assignment/intro_assignment/urls.py
import imp
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intro_assignment/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', showmain, name= 'showmain'),
    path('mainpage/', showpage, name= 'showpage'),
    path('<int:id>', detail, name='detail'),
    path('new/', new, name='new'),
    path('create/', create, name="create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<int:post_id>/create_comment', create_comment, name='create_comment'),
    path('delete_comment/<int:id>', delete_comment, name="delete_comment"),
    path('edit_comment/<int:id>', edit_comment, name="edit_comment"),
    path('update_comment/<int:id>', update_comment, name="update_comment"),
    path('like_toggle/<int:post_id>/', like_toggle, name="like_toggle"),
    path('my_like/<int:user_id>', my_like, name='my_like'),
    path('dislike_toggle/<int:post_id>/', dislike_toggle, name="dislike_toggle"),
    path('my_dislike/<int:user_id>', my_dislike, name='my_dislike'),
]

intro_assignment/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:user_id>', mypage, name="mypage"),
    path('follow/<int:user_id>', follow, name="follow")
]

intro_assignment/users/models.py
from pyexpat import model
from statistics import mode
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


# Create your models here

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followings = models.ManyToManyField("self", related_name="followers", symmetrical=False)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

intro_assignment/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from main.models import Post
from django.contrib.auth.models import User

# Create your views here.
def mypage(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    posts = Post.objects.filter(writer=user)
    
    return render(request, 'users/mypage.html',
    {'posts' : posts, 
    'user': user, 
    'followings' : user.profile.followings.all(),
    'followers' : user.profile.followers.all()
    })

def follow(request, user_id):
    user = request.user
    followed_user = get_object_or_404(User, pk=user_id)
    is_follower = user.profile in followed_user.profile.followers.all()

    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

intro_assignment/users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <h1>{{user.username}}</h1>

    <div class="container">
        <h3>팔로워 {{user.profile.followers.count}}명</h3>
        {% for follower in user.profile.followers.all %}
            <a href="{% url 'users:mypage' follower.user.id %}">{{follower.user.username}}</a>
        {% endfor %}
        <h3>팔로잉 {{user.profile.followings.count}}명</h3>
        {% for following in user.profile.followings.all %}
            <a href="{% url 'users:mypage' following.user.id %}">{{following.user.username}}</a>
        {% endfor %}
        </div>

    {% if request.user != user %}
        {% if request.user.profile in user.profile.followers.all %}
            <a href="{% url 'users:follow' user.id %}"><button type="buttion" class="btn btn-outline-info">언팔로우</button></a>
        {% else %}
            <a href="{% url 'users:follow' user.id %}"><button type="button" class="btn btn-info">팔로우</button></a>
        {% endif %}
    {% endif %}

    <hr>
    <div>
        {% for post in posts %}

        <a href="{% url 'main:detail' post.id %}">{{post.title}}</a><hr>

        {% endfor %}

    </div>
</div>

{% endblock %}